timelines/urls.py
from django.urls import path

from . import views

app_name = 'timelines'
urlpatterns = [
    path('', views.index, name='index'),
    path('timeline/<int:timeline_id>/', views.timeline, name='timeline'),
    path('timeline/create', views.create_timeline, name='create_timeline'),
    path('timeline/edit/<int:timeline_id>/', views.edit_timeline, name='edit_timeline'),
    path('timeline/delete/<int:timeline_id>/', views.delete_timeline, name='delete_timeline'),
    path('timeline/<int:timeline_id>/create_event/', views.create_event, name='create_event'),
    path('event/<int:event_id>/', views.event, name='event'),
    path('event/edit/<int:event_id>/', views.edit_event, name='edit_event'),
    path('event/delete/<int:event_id>/', views.delete_event, name='delete_event'),
]

timely/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('timelines.urls')),
    path('admin/', admin.site.urls),
]

timelines/models.py
from django.utils import timezone
from django.db import models


class Timeline(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    created_date = models.DateTimeField('date created', default=timezone.now)

    def __str__(self):
        return self.name


class Event(models.Model):
    timeline = models.ForeignKey(Timeline, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    start_date = models.DateTimeField('start date')
    end_date = models.DateTimeField('end date')

    def __str__(self):
        return self.name
    
    def is_current(self):
        return self.start_date <= timezone.now() <= self.end_date
    
    def get_duration(self):
        return self.end_date - self.start_date

timelines/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Timeline, Event

def index(request):
    context = {
        'timelines': Timeline.objects.all().order_by('-created_date'),
    }
    return render(request, 'timelines/index.html', context=context)

def timeline(request, timeline_id):
    context = {
        'timeline': Timeline.objects.get(pk=timeline_id),
        'events': Event.objects.filter(timeline=timeline_id).order_by('start_date'),
    }
    return render(request, 'timelines/timeline.html', context=context)

def create_timeline(request):
    if request.method == 'POST':
        timeline = Timeline(name=request.POST['name'], description=request.POST['description'])
        timeline.save()
        return HttpResponse("Added timeline %s!" % timeline.id)
    return render(request, 'timelines/create_timeline.html')

def edit_timeline(request, timeline_id):
    if request.method == 'POST':
        timeline = Timeline.objects.get(pk=timeline_id)
        timeline.name = request.POST['name']
        timeline.description = request.POST['description']
        timeline.save()
        return HttpResponseRedirect(reverse('timelines:timeline', args=(timeline_id,)))
    return HttpResponse("Method not allowed!", status=405) # Method not allowed

def delete_timeline(request, timeline_id):
    if request.method == 'POST':
        Timeline.objects.get(pk=timeline_id).delete()
        return HttpResponseRedirect(reverse('timelines:index'))

def event(request, event_id):
    return HttpResponse("Hello from event %s!" % event_id)

def create_event(request, timeline_id):
    if request.method == 'POST':
        start_date = request.POST['start_date'] + ' ' + request.POST['start_time']
        end_date = request.POST['end_date'] + ' ' + request.POST['end_time']
        event = Event(
            timeline=Timeline.objects.get(pk=timeline_id),
            name=request.POST['name'],
            description=request.POST['description'],
            start_date=start_date,
            end_date=end_date,
        )
        event.save()
        return HttpResponseRedirect(reverse('timelines:timeline', args=(timeline_id,)))
    return render(request, 'timelines/create_event.html', context={'timeline_id': timeline_id})

def edit_event(request, event_id):
    if request.method == 'POST':
        event = Event.objects.get(pk=event_id)
        event.name = request.POST['name']
        event.description = request.POST['description']
        event.start_date = request.POST['start_date']
        event.end_date = request.POST['end_date']
        event.save()
        return HttpResponseRedirect(reverse('timelines:timeline', args=(event.timeline.id,)))

def delete_event(request, event_id):
    if request.method == 'POST':
        event = Event.objects.get(pk=event_id)
        timeline_id = event.timeline.id
        event.delete()
        return HttpResponseRedirect(reverse('timelines:timeline', args=(timeline_id,)))

timelines/templates/timelines/base.html
<!DOCTYPE html>
<html lang="en">
{% load django_bootstrap5 %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="high-rolls">
    <meta name="generator" content="high-rolls">
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}">
    {% load static %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/fontawesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/brands.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesomefree/css/solid.css' %}">
    <link rel="stylesheet" href="{% static 'timelines/css/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="col-lg-8 mx-auto p-4 py-md-5">
        <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
            <a href="{% url 'timelines:index' %}" class="d-flex align-items-center text-body-emphasis text-decoration-none">
                <span class="fs-4">Timelines</span>
            </a>
        </header>
        <main>
            {% block content %}
            {% endblock content %}
        </main>
        <footer class="pt-5 my-5 text-body-secondary border-top"> Created by high-rolls @ 2023 </footer>
    </div>
    {% bootstrap_javascript %}
    <script src="{% static 'timelines/js/tooltips.js' %}" type="text/javascript"></script>
</body>
</html>

timelines/templates/timelines/create_timeline.html
{% extends 'timelines/base.html' %}
{% block title %}Create Timeline{% endblock title %}
{% block content %}
    <h2>Create Timeline</h2>
    <form action="{% url 'timelines:create_timeline' %}" method="post" class="form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>
        <!-- text input for description -->
        <div class="mb-3">
            <label for="description">Description</label>
            <input type="text" name="description" id="description" class="form-control" required>
        </div>
        <!-- submit button -->
        <button type="submit" class="btn btn-primary">Create</button>
        <!-- cancel button -->
        <a href="{% url 'timelines:index' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

timelines/templates/timelines/index.html
{% extends 'timelines/base.html' %}
{% block title %}Timelines{% endblock %}
{% block content %}
<a href="{% url 'timelines:create_timeline' %}">Add a new timeline</a>
<!-- each header links to the timeline's page -->
{% for timeline in timelines %}
<div class="timeline">
    <h1><a href="{% url 'timelines:timeline' timeline.id %}">{{ timeline.name }}</a></h1>
    <p>{{ timeline.description }}</p>
</div>
{% endfor %}
{% endblock %}

timelines/templates/timelines/timeline.html
{% extends "timelines/base.html" %}
<!-- displays a list of events -->
{% block title %}{{ timeline.name }}{% endblock title %}

{% block content %}
{% load static %}
{% load tz %}
<script src="{% static 'timelines/js/timeline.js' %}"></script>
<div class="row bg-light mb-3">
    <div class="col">
        <h1>{{ timeline.name }}</h1>
        <p>{{ timeline.description }}</p>
    </div>
    <div class="col-md-auto">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editTimelineModal">
            Edit
        </button>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteTimelineModal">
            Delete
        </button>
    </div>
</div>
<div class="row">
    {% for event in events %}
        <div class="col-lg-6 col-xxl-4 d-flex align-items-stretch">
            <div class="card mb-3 w-100" id="card{{ forloop.counter }}">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h5 class="card-title">{{ event.name }}</h5>
                        </div>
                        <div class="col-md-auto">
                            <i class="fa-solid fa-clock" data-bs-toggle="tooltip" data-bs-html="true" title="Starts: {{ event.start_date|localtime }}<br>Ends: {{ event.end_date|localtime }}"></i>
                            <a class="link-unstyled mr1" type="button" data-bs-toggle="modal" data-bs-target="#editEventModal">
                                <i class="fa-solid fa-pencil"></i>
                            </a>
                            <a class="link-unstyled fg-danger" type="button" data-bs-toggle="modal" data-bs-target="#deleteEventModal">
                                <i class="fa-solid fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ event.description }}</p>
                </div>
                <div class="card-footer">
                    <span class="badge text-wrap" id="timeCounter{{ forloop.counter }}"></span>
                    <script>
                        startCountDown({{ forloop.counter }}, new Date("{{ event.start_date.isoformat }}").getTime(), new Date("{{ event.end_date.isoformat }}").getTime());
                    </script>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<div class="row">
    <!-- add event button -->
    <div class="col">
        <button id="addEventButton" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addEventModal">
            Add Event
        </button>
    </div>
</div>
    <!-- Modal -->
<div class="modal fade" id="deleteTimelineModal" tabindex="-1" aria-labelledby="deleteTimelineModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Timeline</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
        Do you really want to delete this timeline?
        </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <form action="{% url 'timelines:delete_timeline' timeline.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes</button>
        </form>
        </div>
    </div>
    </div>
</div>
<!-- edit timeline modal -->
<div class="modal fade" id="editTimelineModal" aria-labelledby="editTimelineModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editTimelineModalLabel">Edit Timeline</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'timelines:edit_timeline' timeline.id %}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" value="{{ timeline.name }}" class="form-control" id="name" name="name">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Description</label>
                        <textarea class="form-control" id="description" name="description">{{ timeline.description }}</textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- add event modal -->
<div class="modal fade" id="addEventModal" aria-labelledby="addEventModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addEventModalLabel">Add Event</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'timelines:create_event' timeline.id %}" method="post">
                <div class="modal-body">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" value="" class="form-control" id="name" name="name" required aria-required="true">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Description</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="start_date" class="form-label">Start Date</label>
                        <input type="date" value="" class="form-control" id="start_date" name="start_date" required aria-required="true">
                    </div>
                    <div class="mb-3">
                        <label for="end_date" class="form-label">End Date</label>
                        <input type="date" value="" class="form-control" id="end_date" name="end_date">
                    </div>
                    <div class="mb-3">
                        <label for="start_time" class="form-label">Start Time</label>
                        <input type="time" value="00:00" class="form-control" id="start_time" name="start_time" required aria-required="true">
                    </div>
                    <div class="mb-3">
                        <label for="end_time" class="form-label">End Time</label>
                        <input type="time" value="00:00" class="form-control" id="end_time" name="end_time">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Event</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src={% static "timelines/js/timeline-end.js" %}></script>
{% endblock content %}